<?php
/**
 * DS PHP Edit — central configuration.
 *
 * Ships with working defaults; the app runs with zero edits. The only required
 * operator action is providing the DeepSeek key in K.dat (repo root).
 *
 * All paths derive from __DIR__ so the folder is path-independent (drop it
 * anywhere on a PHP host and it works). No absolute filesystem literals.
 *
 * @author  g023 (https://github.com/g023/)
 * @license MIT
 */

if (defined('DSPE_CONFIG_LOADED')) {
    return;
}
define('DSPE_CONFIG_LOADED', true);

// --- Core paths (all relative to repo root) -------------------------------
define('APP_ROOT', __DIR__);
define('LIB_DIR', APP_ROOT . '/lib');
define('API_DIR', APP_ROOT . '/api');
define('WORK_DIR', APP_ROOT . '/working_folder');
define('UPLOAD_DIR', WORK_DIR . '/uploads');
define('THUMB_DIR', UPLOAD_DIR . '/.thumbs');
define('BACKUP_DIR', WORK_DIR . '/g023_backups');
define('HISTORY_FILE', WORK_DIR . '/g023_history.json');
define('KEY_FILE', APP_ROOT . '/K.dat');

// Names filtered out of the user-facing file picker (app-managed state).
define('HIDDEN_NAMES', ['g023_history.json', 'g023_backups', 'uploads']);

// --- DeepSeek model policy ------------------------------------------------
// Flash is the default EVERYWHERE. Pro is opt-in only (never default).
define('DEFAULT_MODEL', 'deepseek-v4-flash');
define('PRO_MODEL', 'deepseek-v4-pro');
define('ALLOWED_MODELS', [DEFAULT_MODEL, PRO_MODEL]);
// NOTE: the DeepSeek endpoint URL lives ONLY in lib/ds4.php (the single
// connector) so all provider-contact logic is in exactly one place.
define('DEEPSEEK_TIMEOUT', 120);   // seconds; configurable

// --- Limits ---------------------------------------------------------------
define('MAX_UPLOAD_BYTES', 25 * 1024 * 1024);       // 25 MB
define('MAX_EDIT_FILE_BYTES', 5 * 1024 * 1024);     // editor file cap
define('THUMB_MAX', 240);                            // thumbnail longest edge
define('PREVIEW_TIMEOUT', 15);                       // seconds for preview exec
define('PREVIEW_MEMORY', '128M');
define('HISTORY_MAX_CONVERSATIONS', 100);            // rotation cap
define('BACKUP_RETENTION', 20);                      // keep N most recent
define('SESSION_IDLE_TIMEOUT', 8 * 3600);           // 8 hours

// --- Upload MIME allowlist: mime => stored extension ----------------------
define('UPLOAD_MIME_MAP', [
    'image/jpeg'      => 'jpg',
    'image/png'       => 'png',
    'image/gif'       => 'gif',
    'image/webp'      => 'webp',
    'image/bmp'       => 'bmp',
    'image/svg+xml'   => 'svg',
    'application/pdf' => 'pdf',
    'audio/mpeg'      => 'mp3',
    'audio/wav'       => 'wav',
    'audio/ogg'       => 'ogg',
    'audio/mp4'       => 'm4a',
    'video/mp4'       => 'mp4',
    'video/webm'      => 'webm',
    'text/plain'      => 'txt',
]);

// MIME types we re-encode through GD on ingest (raster images only).
define('GD_REENCODE_MIME', ['image/jpeg', 'image/png', 'image/gif', 'image/webp', 'image/bmp']);

// --- Feature flags --------------------------------------------------------
define('AUTO_BACKUP_ON_SAVE', false);   // opt-in
define('CSP_ENFORCE', true);            // false => Content-Security-Policy-Report-Only

// Ensure required runtime directories/files exist (self-creating state).
function dspe_bootstrap_state(): void
{
    foreach ([WORK_DIR, UPLOAD_DIR, THUMB_DIR, BACKUP_DIR] as $dir) {
        if (!is_dir($dir)) {
            @mkdir($dir, 0775, true);
        }
    }
    if (!is_file(HISTORY_FILE)) {
        @file_put_contents(HISTORY_FILE, json_encode(['conversations' => []]));
    }
    // Drop a no-execute guard into the upload dir if absent.
    $htaccess = UPLOAD_DIR . '/.htaccess';
    if (!is_file($htaccess)) {
        @file_put_contents($htaccess, dspe_upload_htaccess());
    }
}

function dspe_upload_htaccess(): string
{
    // Portable across mod_php AND PHP-FPM/FastCGI: we do NOT use `php_flag`
    // (mod_php-only — it 500s under FPM). Instead we deny access to any
    // script-y file and strip handlers/types, wrapped so an unavailable
    // module never breaks the directory.
    // No `php_flag`/`php_admin_flag` here: those are rejected in .htaccess on
    // many servers (php_admin_* is never permitted in .htaccess, and a single
    // disallowed directive 500s the whole directory). Denying the script
    // extensions outright + stripping handlers is portable and sufficient.
    return <<<HT
# Auto-generated by DS PHP Edit — uploaded media must never execute as code.
<FilesMatch "\\.(php|phtml|php3|php4|php5|php7|phps|pht|phar|cgi|pl|py|asp|aspx|sh|htaccess)$">
    Require all denied
</FilesMatch>
<IfModule mod_mime.c>
    RemoveHandler .php .phtml .php3 .php4 .php5 .php7 .phps .pht .phar
    RemoveType .php .phtml .php3 .php4 .php5 .php7 .phps .pht .phar
</IfModule>
<IfModule mod_autoindex.c>
    IndexIgnore *
</IfModule>
HT;
}
